// 全球国家/地区数据
export interface CountryData {
  key: string;
  domainCode: string;    // 国际域名缩写
  countryName: string;   // 国家或地区
  englishName: string;   // 英文名
  phoneCode: string;     // 电话代码
}

export const countryData: CountryData[] = [
  { key: '1', domainCode: 'AD', countryName: '安道尔', englishName: 'Andorra', phoneCode: '+376' },
  { key: '2', domainCode: 'AE', countryName: '阿联酋', englishName: 'United Arab Emirates', phoneCode: '+971' },
  { key: '3', domainCode: 'AF', countryName: '阿富汗', englishName: 'Afghanistan', phoneCode: '+93' },
  { key: '4', domainCode: 'AG', countryName: '安提瓜和巴布达', englishName: 'Antigua and Barbuda', phoneCode: '+1-268' },
  { key: '5', domainCode: 'AI', countryName: '安圭拉', englishName: 'Anguilla', phoneCode: '+1-264' },
  { key: '6', domainCode: 'AL', countryName: '阿尔巴尼亚', englishName: 'Albania', phoneCode: '+355' },
  { key: '7', domainCode: 'AM', countryName: '亚美尼亚', englishName: 'Armenia', phoneCode: '+374' },
  { key: '8', domainCode: 'AO', countryName: '安哥拉', englishName: 'Angola', phoneCode: '+244' },
  { key: '9', domainCode: 'AQ', countryName: '南极洲', englishName: 'Antarctica', phoneCode: '+672' },
  { key: '10', domainCode: 'AR', countryName: '阿根廷', englishName: 'Argentina', phoneCode: '+54' },
  { key: '11', domainCode: 'AS', countryName: '美属萨摩亚', englishName: 'American Samoa', phoneCode: '+1-684' },
  { key: '12', domainCode: 'AT', countryName: '奥地利', englishName: 'Austria', phoneCode: '+43' },
  { key: '13', domainCode: 'AU', countryName: '澳大利亚', englishName: 'Australia', phoneCode: '+61' },
  { key: '14', domainCode: 'AW', countryName: '阿鲁巴', englishName: 'Aruba', phoneCode: '+297' },
  { key: '15', domainCode: 'AX', countryName: '奥兰群岛', englishName: 'Aland Islands', phoneCode: '+358' },
  { key: '16', domainCode: 'AZ', countryName: '阿塞拜疆', englishName: 'Azerbaijan', phoneCode: '+994' },
  { key: '17', domainCode: 'BA', countryName: '波黑', englishName: 'Bosnia and Herzegovina', phoneCode: '+387' },
  { key: '18', domainCode: 'BB', countryName: '巴巴多斯', englishName: 'Barbados', phoneCode: '+1-246' },
  { key: '19', domainCode: 'BD', countryName: '孟加拉国', englishName: 'Bangladesh', phoneCode: '+880' },
  { key: '20', domainCode: 'BE', countryName: '比利时', englishName: 'Belgium', phoneCode: '+32' },
  { key: '21', domainCode: 'BF', countryName: '布基纳法索', englishName: 'Burkina Faso', phoneCode: '+226' },
  { key: '22', domainCode: 'BG', countryName: '保加利亚', englishName: 'Bulgaria', phoneCode: '+359' },
  { key: '23', domainCode: 'BH', countryName: '巴林', englishName: 'Bahrain', phoneCode: '+973' },
  { key: '24', domainCode: 'BI', countryName: '布隆迪', englishName: 'Burundi', phoneCode: '+257' },
  { key: '25', domainCode: 'BJ', countryName: '贝宁', englishName: 'Benin', phoneCode: '+229' },
  { key: '26', domainCode: 'BL', countryName: '圣巴泰勒米', englishName: 'Saint Barthelemy', phoneCode: '+590' },
  { key: '27', domainCode: 'BM', countryName: '百慕大', englishName: 'Bermuda', phoneCode: '+1-441' },
  { key: '28', domainCode: 'BN', countryName: '文莱', englishName: 'Brunei', phoneCode: '+673' },
  { key: '29', domainCode: 'BO', countryName: '玻利维亚', englishName: 'Bolivia', phoneCode: '+591' },
  { key: '30', domainCode: 'BQ', countryName: '荷兰加勒比区', englishName: 'Caribbean Netherlands', phoneCode: '+599' },
  { key: '31', domainCode: 'BR', countryName: '巴西', englishName: 'Brazil', phoneCode: '+55' },
  { key: '32', domainCode: 'BS', countryName: '巴哈马', englishName: 'Bahamas', phoneCode: '+1-242' },
  { key: '33', domainCode: 'BT', countryName: '不丹', englishName: 'Bhutan', phoneCode: '+975' },
  { key: '34', domainCode: 'BW', countryName: '博茨瓦纳', englishName: 'Botswana', phoneCode: '+267' },
  { key: '35', domainCode: 'BY', countryName: '白俄罗斯', englishName: 'Belarus', phoneCode: '+375' },
  { key: '36', domainCode: 'BZ', countryName: '伯利兹', englishName: 'Belize', phoneCode: '+501' },
  { key: '37', domainCode: 'CA', countryName: '加拿大', englishName: 'Canada', phoneCode: '+1' },
  { key: '38', domainCode: 'CC', countryName: '科科斯群岛', englishName: 'Cocos Islands', phoneCode: '+61' },
  { key: '39', domainCode: 'CD', countryName: '刚果(金)', englishName: 'DR Congo', phoneCode: '+243' },
  { key: '40', domainCode: 'CF', countryName: '中非', englishName: 'Central African Republic', phoneCode: '+236' },
  { key: '41', domainCode: 'CG', countryName: '刚果(布)', englishName: 'Republic of the Congo', phoneCode: '+242' },
  { key: '42', domainCode: 'CH', countryName: '瑞士', englishName: 'Switzerland', phoneCode: '+41' },
  { key: '43', domainCode: 'CI', countryName: '科特迪瓦', englishName: 'Ivory Coast', phoneCode: '+225' },
  { key: '44', domainCode: 'CK', countryName: '库克群岛', englishName: 'Cook Islands', phoneCode: '+682' },
  { key: '45', domainCode: 'CL', countryName: '智利', englishName: 'Chile', phoneCode: '+56' },
  { key: '46', domainCode: 'CM', countryName: '喀麦隆', englishName: 'Cameroon', phoneCode: '+237' },
  { key: '47', domainCode: 'CN', countryName: '中国', englishName: 'China', phoneCode: '+86' },
  { key: '48', domainCode: 'CO', countryName: '哥伦比亚', englishName: 'Colombia', phoneCode: '+57' },
  { key: '49', domainCode: 'CR', countryName: '哥斯达黎加', englishName: 'Costa Rica', phoneCode: '+506' },
  { key: '50', domainCode: 'CU', countryName: '古巴', englishName: 'Cuba', phoneCode: '+53' },
  { key: '51', domainCode: 'CV', countryName: '佛得角', englishName: 'Cape Verde', phoneCode: '+238' },
  { key: '52', domainCode: 'CW', countryName: '库拉索', englishName: 'Curacao', phoneCode: '+599' },
  { key: '53', domainCode: 'CX', countryName: '圣诞岛', englishName: 'Christmas Island', phoneCode: '+61' },
  { key: '54', domainCode: 'CY', countryName: '塞浦路斯', englishName: 'Cyprus', phoneCode: '+357' },
  { key: '55', domainCode: 'CZ', countryName: '捷克', englishName: 'Czech Republic', phoneCode: '+420' },
  { key: '56', domainCode: 'DE', countryName: '德国', englishName: 'Germany', phoneCode: '+49' },
  { key: '57', domainCode: 'DJ', countryName: '吉布提', englishName: 'Djibouti', phoneCode: '+253' },
  { key: '58', domainCode: 'DK', countryName: '丹麦', englishName: 'Denmark', phoneCode: '+45' },
  { key: '59', domainCode: 'DM', countryName: '多米尼克', englishName: 'Dominica', phoneCode: '+1-767' },
  { key: '60', domainCode: 'DO', countryName: '多米尼加', englishName: 'Dominican Republic', phoneCode: '+1-809' },
  { key: '61', domainCode: 'DZ', countryName: '阿尔及利亚', englishName: 'Algeria', phoneCode: '+213' },
  { key: '62', domainCode: 'EC', countryName: '厄瓜多尔', englishName: 'Ecuador', phoneCode: '+593' },
  { key: '63', domainCode: 'EE', countryName: '爱沙尼亚', englishName: 'Estonia', phoneCode: '+372' },
  { key: '64', domainCode: 'EG', countryName: '埃及', englishName: 'Egypt', phoneCode: '+20' },
  { key: '65', domainCode: 'EH', countryName: '西撒哈拉', englishName: 'Western Sahara', phoneCode: '+212' },
  { key: '66', domainCode: 'ER', countryName: '厄立特里亚', englishName: 'Eritrea', phoneCode: '+291' },
  { key: '67', domainCode: 'ES', countryName: '西班牙', englishName: 'Spain', phoneCode: '+34' },
  { key: '68', domainCode: 'ET', countryName: '埃塞俄比亚', englishName: 'Ethiopia', phoneCode: '+251' },
  { key: '69', domainCode: 'FI', countryName: '芬兰', englishName: 'Finland', phoneCode: '+358' },
  { key: '70', domainCode: 'FJ', countryName: '斐济', englishName: 'Fiji', phoneCode: '+679' },
  { key: '71', domainCode: 'FK', countryName: '福克兰群岛', englishName: 'Falkland Islands', phoneCode: '+500' },
  { key: '72', domainCode: 'FM', countryName: '密克罗尼西亚', englishName: 'Micronesia', phoneCode: '+691' },
  { key: '73', domainCode: 'FO', countryName: '法罗群岛', englishName: 'Faroe Islands', phoneCode: '+298' },
  { key: '74', domainCode: 'FR', countryName: '法国', englishName: 'France', phoneCode: '+33' },
  { key: '75', domainCode: 'GA', countryName: '加蓬', englishName: 'Gabon', phoneCode: '+241' },
  { key: '76', domainCode: 'GB', countryName: '英国', englishName: 'United Kingdom', phoneCode: '+44' },
  { key: '77', domainCode: 'GD', countryName: '格林纳达', englishName: 'Grenada', phoneCode: '+1-473' },
  { key: '78', domainCode: 'GE', countryName: '格鲁吉亚', englishName: 'Georgia', phoneCode: '+995' },
  { key: '79', domainCode: 'GF', countryName: '法属圭亚那', englishName: 'French Guiana', phoneCode: '+594' },
  { key: '80', domainCode: 'GG', countryName: '根西岛', englishName: 'Guernsey', phoneCode: '+44' },
  { key: '81', domainCode: 'GH', countryName: '加纳', englishName: 'Ghana', phoneCode: '+233' },
  { key: '82', domainCode: 'GI', countryName: '直布罗陀', englishName: 'Gibraltar', phoneCode: '+350' },
  { key: '83', domainCode: 'GL', countryName: '格陵兰', englishName: 'Greenland', phoneCode: '+299' },
  { key: '84', domainCode: 'GM', countryName: '冈比亚', englishName: 'Gambia', phoneCode: '+220' },
  { key: '85', domainCode: 'GN', countryName: '几内亚', englishName: 'Guinea', phoneCode: '+224' },
  { key: '86', domainCode: 'GP', countryName: '瓜德罗普', englishName: 'Guadeloupe', phoneCode: '+590' },
  { key: '87', domainCode: 'GQ', countryName: '赤道几内亚', englishName: 'Equatorial Guinea', phoneCode: '+240' },
  { key: '88', domainCode: 'GR', countryName: '希腊', englishName: 'Greece', phoneCode: '+30' },
  { key: '89', domainCode: 'GT', countryName: '危地马拉', englishName: 'Guatemala', phoneCode: '+502' },
  { key: '90', domainCode: 'GU', countryName: '关岛', englishName: 'Guam', phoneCode: '+1-671' },
  { key: '91', domainCode: 'GW', countryName: '几内亚比绍', englishName: 'Guinea-Bissau', phoneCode: '+245' },
  { key: '92', domainCode: 'GY', countryName: '圭亚那', englishName: 'Guyana', phoneCode: '+592' },
  { key: '93', domainCode: 'HK', countryName: '中国香港', englishName: 'Hong Kong', phoneCode: '+852' },
  { key: '94', domainCode: 'HN', countryName: '洪都拉斯', englishName: 'Honduras', phoneCode: '+504' },
  { key: '95', domainCode: 'HR', countryName: '克罗地亚', englishName: 'Croatia', phoneCode: '+385' },
  { key: '96', domainCode: 'HT', countryName: '海地', englishName: 'Haiti', phoneCode: '+509' },
  { key: '97', domainCode: 'HU', countryName: '匈牙利', englishName: 'Hungary', phoneCode: '+36' },
  { key: '98', domainCode: 'ID', countryName: '印度尼西亚', englishName: 'Indonesia', phoneCode: '+62' },
  { key: '99', domainCode: 'IE', countryName: '爱尔兰', englishName: 'Ireland', phoneCode: '+353' },
  { key: '100', domainCode: 'IL', countryName: '以色列', englishName: 'Israel', phoneCode: '+972' },
  { key: '101', domainCode: 'IM', countryName: '马恩岛', englishName: 'Isle of Man', phoneCode: '+44' },
  { key: '102', domainCode: 'IN', countryName: '印度', englishName: 'India', phoneCode: '+91' },
  { key: '103', domainCode: 'IO', countryName: '英属印度洋领地', englishName: 'British Indian Ocean Territory', phoneCode: '+246' },
  { key: '104', domainCode: 'IQ', countryName: '伊拉克', englishName: 'Iraq', phoneCode: '+964' },
  { key: '105', domainCode: 'IR', countryName: '伊朗', englishName: 'Iran', phoneCode: '+98' },
  { key: '106', domainCode: 'IS', countryName: '冰岛', englishName: 'Iceland', phoneCode: '+354' },
  { key: '107', domainCode: 'IT', countryName: '意大利', englishName: 'Italy', phoneCode: '+39' },
  { key: '108', domainCode: 'JE', countryName: '泽西岛', englishName: 'Jersey', phoneCode: '+44' },
  { key: '109', domainCode: 'JM', countryName: '牙买加', englishName: 'Jamaica', phoneCode: '+1-876' },
  { key: '110', domainCode: 'JO', countryName: '约旦', englishName: 'Jordan', phoneCode: '+962' },
  { key: '111', domainCode: 'JP', countryName: '日本', englishName: 'Japan', phoneCode: '+81' },
  { key: '112', domainCode: 'KE', countryName: '肯尼亚', englishName: 'Kenya', phoneCode: '+254' },
  { key: '113', domainCode: 'KG', countryName: '吉尔吉斯斯坦', englishName: 'Kyrgyzstan', phoneCode: '+996' },
  { key: '114', domainCode: 'KH', countryName: '柬埔寨', englishName: 'Cambodia', phoneCode: '+855' },
  { key: '115', domainCode: 'KI', countryName: '基里巴斯', englishName: 'Kiribati', phoneCode: '+686' },
  { key: '116', domainCode: 'KM', countryName: '科摩罗', englishName: 'Comoros', phoneCode: '+269' },
  { key: '117', domainCode: 'KN', countryName: '圣基茨和尼维斯', englishName: 'Saint Kitts and Nevis', phoneCode: '+1-869' },
  { key: '118', domainCode: 'KP', countryName: '朝鲜', englishName: 'North Korea', phoneCode: '+850' },
  { key: '119', domainCode: 'KR', countryName: '韩国', englishName: 'South Korea', phoneCode: '+82' },
  { key: '120', domainCode: 'KW', countryName: '科威特', englishName: 'Kuwait', phoneCode: '+965' },
  { key: '121', domainCode: 'KY', countryName: '开曼群岛', englishName: 'Cayman Islands', phoneCode: '+1-345' },
  { key: '122', domainCode: 'KZ', countryName: '哈萨克斯坦', englishName: 'Kazakhstan', phoneCode: '+7' },
  { key: '123', domainCode: 'LA', countryName: '老挝', englishName: 'Laos', phoneCode: '+856' },
  { key: '124', domainCode: 'LB', countryName: '黎巴嫩', englishName: 'Lebanon', phoneCode: '+961' },
  { key: '125', domainCode: 'LC', countryName: '圣卢西亚', englishName: 'Saint Lucia', phoneCode: '+1-758' },
  { key: '126', domainCode: 'LI', countryName: '列支敦士登', englishName: 'Liechtenstein', phoneCode: '+423' },
  { key: '127', domainCode: 'LK', countryName: '斯里兰卡', englishName: 'Sri Lanka', phoneCode: '+94' },
  { key: '128', domainCode: 'LR', countryName: '利比里亚', englishName: 'Liberia', phoneCode: '+231' },
  { key: '129', domainCode: 'LS', countryName: '莱索托', englishName: 'Lesotho', phoneCode: '+266' },
  { key: '130', domainCode: 'LT', countryName: '立陶宛', englishName: 'Lithuania', phoneCode: '+370' },
  { key: '131', domainCode: 'LU', countryName: '卢森堡', englishName: 'Luxembourg', phoneCode: '+352' },
  { key: '132', domainCode: 'LV', countryName: '拉脱维亚', englishName: 'Latvia', phoneCode: '+371' },
  { key: '133', domainCode: 'LY', countryName: '利比亚', englishName: 'Libya', phoneCode: '+218' },
  { key: '134', domainCode: 'MA', countryName: '摩洛哥', englishName: 'Morocco', phoneCode: '+212' },
  { key: '135', domainCode: 'MC', countryName: '摩纳哥', englishName: 'Monaco', phoneCode: '+377' },
  { key: '136', domainCode: 'MD', countryName: '摩尔多瓦', englishName: 'Moldova', phoneCode: '+373' },
  { key: '137', domainCode: 'ME', countryName: '黑山', englishName: 'Montenegro', phoneCode: '+382' },
  { key: '138', domainCode: 'MF', countryName: '法属圣马丁', englishName: 'Saint Martin', phoneCode: '+590' },
  { key: '139', domainCode: 'MG', countryName: '马达加斯加', englishName: 'Madagascar', phoneCode: '+261' },
  { key: '140', domainCode: 'MH', countryName: '马绍尔群岛', englishName: 'Marshall Islands', phoneCode: '+692' },
  { key: '141', domainCode: 'MK', countryName: '北马其顿', englishName: 'North Macedonia', phoneCode: '+389' },
  { key: '142', domainCode: 'ML', countryName: '马里', englishName: 'Mali', phoneCode: '+223' },
  { key: '143', domainCode: 'MM', countryName: '缅甸', englishName: 'Myanmar', phoneCode: '+95' },
  { key: '144', domainCode: 'MN', countryName: '蒙古', englishName: 'Mongolia', phoneCode: '+976' },
  { key: '145', domainCode: 'MO', countryName: '中国澳门', englishName: 'Macau', phoneCode: '+853' },
  { key: '146', domainCode: 'MP', countryName: '北马里亚纳群岛', englishName: 'Northern Mariana Islands', phoneCode: '+1-670' },
  { key: '147', domainCode: 'MQ', countryName: '马提尼克', englishName: 'Martinique', phoneCode: '+596' },
  { key: '148', domainCode: 'MR', countryName: '毛里塔尼亚', englishName: 'Mauritania', phoneCode: '+222' },
  { key: '149', domainCode: 'MS', countryName: '蒙特塞拉特', englishName: 'Montserrat', phoneCode: '+1-664' },
  { key: '150', domainCode: 'MT', countryName: '马耳他', englishName: 'Malta', phoneCode: '+356' },
  { key: '151', domainCode: 'MU', countryName: '毛里求斯', englishName: 'Mauritius', phoneCode: '+230' },
  { key: '152', domainCode: 'MV', countryName: '马尔代夫', englishName: 'Maldives', phoneCode: '+960' },
  { key: '153', domainCode: 'MW', countryName: '马拉维', englishName: 'Malawi', phoneCode: '+265' },
  { key: '154', domainCode: 'MX', countryName: '墨西哥', englishName: 'Mexico', phoneCode: '+52' },
  { key: '155', domainCode: 'MY', countryName: '马来西亚', englishName: 'Malaysia', phoneCode: '+60' },
  { key: '156', domainCode: 'MZ', countryName: '莫桑比克', englishName: 'Mozambique', phoneCode: '+258' },
  { key: '157', domainCode: 'NA', countryName: '纳米比亚', englishName: 'Namibia', phoneCode: '+264' },
  { key: '158', domainCode: 'NC', countryName: '新喀里多尼亚', englishName: 'New Caledonia', phoneCode: '+687' },
  { key: '159', domainCode: 'NE', countryName: '尼日尔', englishName: 'Niger', phoneCode: '+227' },
  { key: '160', domainCode: 'NF', countryName: '诺福克岛', englishName: 'Norfolk Island', phoneCode: '+672' },
  { key: '161', domainCode: 'NG', countryName: '尼日利亚', englishName: 'Nigeria', phoneCode: '+234' },
  { key: '162', domainCode: 'NI', countryName: '尼加拉瓜', englishName: 'Nicaragua', phoneCode: '+505' },
  { key: '163', domainCode: 'NL', countryName: '荷兰', englishName: 'Netherlands', phoneCode: '+31' },
  { key: '164', domainCode: 'NO', countryName: '挪威', englishName: 'Norway', phoneCode: '+47' },
  { key: '165', domainCode: 'NP', countryName: '尼泊尔', englishName: 'Nepal', phoneCode: '+977' },
  { key: '166', domainCode: 'NR', countryName: '瑙鲁', englishName: 'Nauru', phoneCode: '+674' },
  { key: '167', domainCode: 'NU', countryName: '纽埃', englishName: 'Niue', phoneCode: '+683' },
  { key: '168', domainCode: 'NZ', countryName: '新西兰', englishName: 'New Zealand', phoneCode: '+64' },
  { key: '169', domainCode: 'OM', countryName: '阿曼', englishName: 'Oman', phoneCode: '+968' },
  { key: '170', domainCode: 'PA', countryName: '巴拿马', englishName: 'Panama', phoneCode: '+507' },
  { key: '171', domainCode: 'PE', countryName: '秘鲁', englishName: 'Peru', phoneCode: '+51' },
  { key: '172', domainCode: 'PF', countryName: '法属波利尼西亚', englishName: 'French Polynesia', phoneCode: '+689' },
  { key: '173', domainCode: 'PG', countryName: '巴布亚新几内亚', englishName: 'Papua New Guinea', phoneCode: '+675' },
  { key: '174', domainCode: 'PH', countryName: '菲律宾', englishName: 'Philippines', phoneCode: '+63' },
  { key: '175', domainCode: 'PK', countryName: '巴基斯坦', englishName: 'Pakistan', phoneCode: '+92' },
  { key: '176', domainCode: 'PL', countryName: '波兰', englishName: 'Poland', phoneCode: '+48' },
  { key: '177', domainCode: 'PM', countryName: '圣皮埃尔和密克隆', englishName: 'Saint Pierre and Miquelon', phoneCode: '+508' },
  { key: '178', domainCode: 'PN', countryName: '皮特凯恩群岛', englishName: 'Pitcairn Islands', phoneCode: '+64' },
  { key: '179', domainCode: 'PR', countryName: '波多黎各', englishName: 'Puerto Rico', phoneCode: '+1-787' },
  { key: '180', domainCode: 'PS', countryName: '巴勒斯坦', englishName: 'Palestine', phoneCode: '+970' },
  { key: '181', domainCode: 'PT', countryName: '葡萄牙', englishName: 'Portugal', phoneCode: '+351' },
  { key: '182', domainCode: 'PW', countryName: '帕劳', englishName: 'Palau', phoneCode: '+680' },
  { key: '183', domainCode: 'PY', countryName: '巴拉圭', englishName: 'Paraguay', phoneCode: '+595' },
  { key: '184', domainCode: 'QA', countryName: '卡塔尔', englishName: 'Qatar', phoneCode: '+974' },
  { key: '185', domainCode: 'RE', countryName: '留尼汪', englishName: 'Reunion', phoneCode: '+262' },
  { key: '186', domainCode: 'RO', countryName: '罗马尼亚', englishName: 'Romania', phoneCode: '+40' },
  { key: '187', domainCode: 'RS', countryName: '塞尔维亚', englishName: 'Serbia', phoneCode: '+381' },
  { key: '188', domainCode: 'RU', countryName: '俄罗斯', englishName: 'Russia', phoneCode: '+7' },
  { key: '189', domainCode: 'RW', countryName: '卢旺达', englishName: 'Rwanda', phoneCode: '+250' },
  { key: '190', domainCode: 'SA', countryName: '沙特阿拉伯', englishName: 'Saudi Arabia', phoneCode: '+966' },
  { key: '191', domainCode: 'SB', countryName: '所罗门群岛', englishName: 'Solomon Islands', phoneCode: '+677' },
  { key: '192', domainCode: 'SC', countryName: '塞舌尔', englishName: 'Seychelles', phoneCode: '+248' },
  { key: '193', domainCode: 'SD', countryName: '苏丹', englishName: 'Sudan', phoneCode: '+249' },
  { key: '194', domainCode: 'SE', countryName: '瑞典', englishName: 'Sweden', phoneCode: '+46' },
  { key: '195', domainCode: 'SG', countryName: '新加坡', englishName: 'Singapore', phoneCode: '+65' },
  { key: '196', domainCode: 'SH', countryName: '圣赫勒拿', englishName: 'Saint Helena', phoneCode: '+290' },
  { key: '197', domainCode: 'SI', countryName: '斯洛文尼亚', englishName: 'Slovenia', phoneCode: '+386' },
  { key: '198', domainCode: 'SJ', countryName: '斯瓦尔巴和扬马延', englishName: 'Svalbard and Jan Mayen', phoneCode: '+47' },
  { key: '199', domainCode: 'SK', countryName: '斯洛伐克', englishName: 'Slovakia', phoneCode: '+421' },
  { key: '200', domainCode: 'SL', countryName: '塞拉利昂', englishName: 'Sierra Leone', phoneCode: '+232' },
  { key: '201', domainCode: 'SM', countryName: '圣马力诺', englishName: 'San Marino', phoneCode: '+378' },
  { key: '202', domainCode: 'SN', countryName: '塞内加尔', englishName: 'Senegal', phoneCode: '+221' },
  { key: '203', domainCode: 'SO', countryName: '索马里', englishName: 'Somalia', phoneCode: '+252' },
  { key: '204', domainCode: 'SR', countryName: '苏里南', englishName: 'Suriname', phoneCode: '+597' },
  { key: '205', domainCode: 'SS', countryName: '南苏丹', englishName: 'South Sudan', phoneCode: '+211' },
  { key: '206', domainCode: 'ST', countryName: '圣多美和普林西比', englishName: 'Sao Tome and Principe', phoneCode: '+239' },
  { key: '207', domainCode: 'SV', countryName: '萨尔瓦多', englishName: 'El Salvador', phoneCode: '+503' },
  { key: '208', domainCode: 'SX', countryName: '荷属圣马丁', englishName: 'Sint Maarten', phoneCode: '+1-721' },
  { key: '209', domainCode: 'SY', countryName: '叙利亚', englishName: 'Syria', phoneCode: '+963' },
  { key: '210', domainCode: 'SZ', countryName: '斯威士兰', englishName: 'Eswatini', phoneCode: '+268' },
  { key: '211', domainCode: 'TC', countryName: '特克斯和凯科斯群岛', englishName: 'Turks and Caicos Islands', phoneCode: '+1-649' },
  { key: '212', domainCode: 'TD', countryName: '乍得', englishName: 'Chad', phoneCode: '+235' },
  { key: '213', domainCode: 'TG', countryName: '多哥', englishName: 'Togo', phoneCode: '+228' },
  { key: '214', domainCode: 'TH', countryName: '泰国', englishName: 'Thailand', phoneCode: '+66' },
  { key: '215', domainCode: 'TJ', countryName: '塔吉克斯坦', englishName: 'Tajikistan', phoneCode: '+992' },
  { key: '216', domainCode: 'TK', countryName: '托克劳', englishName: 'Tokelau', phoneCode: '+690' },
  { key: '217', domainCode: 'TL', countryName: '东帝汶', englishName: 'Timor-Leste', phoneCode: '+670' },
  { key: '218', domainCode: 'TM', countryName: '土库曼斯坦', englishName: 'Turkmenistan', phoneCode: '+993' },
  { key: '219', domainCode: 'TN', countryName: '突尼斯', englishName: 'Tunisia', phoneCode: '+216' },
  { key: '220', domainCode: 'TO', countryName: '汤加', englishName: 'Tonga', phoneCode: '+676' },
  { key: '221', domainCode: 'TR', countryName: '土耳其', englishName: 'Turkey', phoneCode: '+90' },
  { key: '222', domainCode: 'TT', countryName: '特立尼达和多巴哥', englishName: 'Trinidad and Tobago', phoneCode: '+1-868' },
  { key: '223', domainCode: 'TV', countryName: '图瓦卢', englishName: 'Tuvalu', phoneCode: '+688' },
  { key: '224', domainCode: 'TW', countryName: '中国台湾', englishName: 'Taiwan', phoneCode: '+886' },
  { key: '225', domainCode: 'TZ', countryName: '坦桑尼亚', englishName: 'Tanzania', phoneCode: '+255' },
  { key: '226', domainCode: 'UA', countryName: '乌克兰', englishName: 'Ukraine', phoneCode: '+380' },
  { key: '227', domainCode: 'UG', countryName: '乌干达', englishName: 'Uganda', phoneCode: '+256' },
  { key: '228', domainCode: 'US', countryName: '美国', englishName: 'United States', phoneCode: '+1' },
  { key: '229', domainCode: 'UY', countryName: '乌拉圭', englishName: 'Uruguay', phoneCode: '+598' },
  { key: '230', domainCode: 'UZ', countryName: '乌兹别克斯坦', englishName: 'Uzbekistan', phoneCode: '+998' },
  { key: '231', domainCode: 'VA', countryName: '梵蒂冈', englishName: 'Vatican City', phoneCode: '+39' },
  { key: '232', domainCode: 'VC', countryName: '圣文森特和格林纳丁斯', englishName: 'Saint Vincent and the Grenadines', phoneCode: '+1-784' },
  { key: '233', domainCode: 'VE', countryName: '委内瑞拉', englishName: 'Venezuela', phoneCode: '+58' },
  { key: '234', domainCode: 'VG', countryName: '英属维尔京群岛', englishName: 'British Virgin Islands', phoneCode: '+1-284' },
  { key: '235', domainCode: 'VI', countryName: '美属维尔京群岛', englishName: 'U.S. Virgin Islands', phoneCode: '+1-340' },
  { key: '236', domainCode: 'VN', countryName: '越南', englishName: 'Vietnam', phoneCode: '+84' },
  { key: '237', domainCode: 'VU', countryName: '瓦努阿图', englishName: 'Vanuatu', phoneCode: '+678' },
  { key: '238', domainCode: 'WF', countryName: '瓦利斯和富图纳', englishName: 'Wallis and Futuna', phoneCode: '+681' },
  { key: '239', domainCode: 'WS', countryName: '萨摩亚', englishName: 'Samoa', phoneCode: '+685' },
  { key: '240', domainCode: 'XK', countryName: '科索沃', englishName: 'Kosovo', phoneCode: '+383' },
  { key: '241', domainCode: 'YE', countryName: '也门', englishName: 'Yemen', phoneCode: '+967' },
  { key: '242', domainCode: 'YT', countryName: '马约特', englishName: 'Mayotte', phoneCode: '+262' },
  { key: '243', domainCode: 'ZA', countryName: '南非', englishName: 'South Africa', phoneCode: '+27' },
  { key: '244', domainCode: 'ZM', countryName: '赞比亚', englishName: 'Zambia', phoneCode: '+260' },
  { key: '245', domainCode: 'ZW', countryName: '津巴布韦', englishName: 'Zimbabwe', phoneCode: '+263' },
];
